# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: https://akashshanker321.github.io/Resume/
baseurl: /Resume/
title: Akash Shanker
author: Akash Shanker
description: Personal blog and resume
avatar: profile2.png
email: akashshanker78@gmail.com
github: AkashShanker321
twitter: AkashShanker_78
linkedin: akash-shanker-a94891199/
medium: akashshanker78.medium.com
stackoverflow: users/15173261/akash-shanker
#Comment out if you don't want disqus
#disqus: username
#google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
