# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://username.github.io/
baseurl: /home/
title: Akash Shanker
author: Akash Shanker
description: Personal blog and resume
avatar: profile.png
email: yourname@email.com
github: https://github.com/AkashShanker321
twitter: https://twitter.com/AkashShanker_78
linkedin: https://www.linkedin.com/in/akash-shanker-a94891199/
stackoverflow: https://stackoverflow.com/users/15173261/akash-shanker
#Comment out if you don't want disqus
#disqus: username
#google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
